name: e_commerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  page_transition: ^2.0.4
  ionicons: ^0.1.2
  animate_do: ^2.0.0
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.2.15
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.13
  equatable: ^2.0.3
  fluttertoast: ^8.0.9
  dartz: ^0.10.1
  conditional_builder_null_safety: ^0.0.6
  get_it: ^7.2.0
  intl: ^0.17.0
  card_swiper: ^2.0.4
  country_code_picker: ^2.0.2
  flutter_rating_bar: ^4.0.1
  lottie: ^1.2.2
  rflutter_alert: ^2.0.4
  formz: ^0.4.1
  timelines: ^0.1.0
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.1.1
  flutter_slidable: ^1.2.0
  google_maps_flutter: ^2.1.4
  geocoding: ^2.0.4
  geolocator: ^8.2.1
  image_picker: ^0.8.5
  timeline_tile: ^2.0.0
  flutter_stripe: ^3.0.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  image_gallery_saver: ^1.7.1
  permission_handler: ^9.2.0
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Regular.ttf
  - family: NunitoSans
    fonts:
    - asset: assets/fonts/NunitoSans-Regular.ttf
